### ISSUE TITLE
Can't install on windows. fails while downloading the dll

### ISSUE THREAD

**Issue by khalidelboray** [frithnanth/perl6-Archive-Libarchive-Raw#8] opened 2021-02-04 21:23 UTC
Seems like [www.p6c.org](https://www.p6c.org) is down.

**Comment by frithnanth** [comment] 2021-02-05 08:55
I'm sorry I can't help you on this, since the Windows installation part was contributed by Jonathan Worthington.
I can confirm that www.p6c.org is currently unreachable, or at least I can't reach it.
Though I see that a search of `libarchive.dll` on the Internet returns several links, so if you are so inclined, you can clone the repository and edit the Build.pm file inside it, modifying the link that points to that DLL.
I'm sorry I can't be of more help, I have no Windows machine on which to perform a test.
Please, let me know if you're able to solve this issue.

**Comment by khalidelboray** [comment] 2021-02-05 09:13
Thanks for your reply, i will check the available dlls and let you know.

**Comment by frithnanth** [comment] 2021-10-04 16:38
I think I can close this issue, if anything new pops up, please reopen it.

**Closed as completed by frithnanth** 2021-10-04 16:38 UTC
